### ISSUE TITLE
Torbox.yml issues

### ISSUE THREAD

**Issue by matthew73210** [dreulavelle/Prowlarr-Indexers#50]
Hey, cheers for this. Sadly I can't get torbox to work. Copied the torbox.yml into the Custom dir and can find it it prowlarr but i get the folowing error :

```
2024-10-31 15:34:08 [Warn] Cardigann: Request for TorBox Torrents failed with status InternalServerError. Retrying in 1.8765001s. 
2024-10-31 15:34:10 [Warn] Cardigann: Request for TorBox Torrents failed with status InternalServerError. Retrying in 1.4805968s. 
2024-10-31 15:34:12 [Warn] Cardigann: HTTP Error - Res: HTTP/2.0 [GET] https://search-api.torbox.app/torrents/imdb:: 500.InternalServerError (21 bytes)
2024-10-31 15:34:12 Internal Server Error 
2024-10-31 15:34:12 [Warn] Cardigann: Unable to connect to indexer 
2024-10-31 15:34:12 
2024-10-31 15:34:12 [v1.25.4.4818] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://search-api.torbox.app/torrents/imdb:]
2024-10-31 15:34:12    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 697
2024-10-31 15:34:12    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 583
2024-10-31 15:34:12    at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 760
2024-10-31 15:34:12 Internal Server Error
2024-10-31 15:34:12 
2024-10-31 15:34:12 
2024-10-31 15:34:12 [Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
2024-10-31 15:34:12  -- : Unable to connect to indexer, indexer's server is unavailable. Try again later. HTTP request failed: [500:InternalServerError] [GET] at [https://search-api.torbox.app/torrents/imdb:] 
```
 and : 

`Unable to connect to indexer, indexer's server is unavailable. Try again later. HTTP request failed: [500:InternalServerError] [GET] at [https://search-api.torbox.app/torrents/imdb:]
`

Any clues to what settings i'm supposed to use? Not using Radarr, just prowlarr into comet into steamio. Torbox is a bit buggy and won't show the show i search for, but says that torrent exists etc..

**Comment by s1dave-web** [comment]
Also got torbox issues mine reports:
Unable to connect to indexer. Unexpected response status Unauthorized code from indexer request

**Comment by s1dave-web** [comment]
Resolved this by adding API key to Auth header - will try and do a pull request to merge changes

**Comment by dreulavelle** [comment]
merged pr, closing issue. 👌

**Comment by matthew73210** [comment]
Any chance abount adding a torbox usenet version? can this be done in prowlarr?
